defmodule Streampai.Repo.Migrations.AddPassword do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :email, :text, null: false
      add :confirmed_at, :utc_datetime_usec
      add :hashed_password, :text
    end
  end

  def down do
    alter table(:users) do
      remove :hashed_password
      remove :confirmed_at
      modify :email, :text, null: true
    end
  end
end
