defmodule Streampai.Repo.Migrations.AddStreamingAccountExtraData do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:streaming_account) do
      add :extra_data, :map, null: false
    end
  end

  def down do
    alter table(:streaming_account) do
      remove :extra_data
    end
  end
end
