defmodule Streampai.Repo.Migrations.AddStreamingAccount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:streaming_account, primary_key: false) do
      add :user_id, :text, null: false, primary_key: true
      add :platform, :text, null: false, primary_key: true
      add :refresh_token, :text, null: false
      add :access_token, :text, null: false
      add :access_token_expires_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:streaming_account)
  end
end
