defmodule Streampai.Repo.Migrations.Changes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:livestream) do
      modify :started_at, :utc_datetime, null: false
    end

    alter table(:chat_messages) do
      remove :platform_user_id
    end
  end

  def down do
    alter table(:chat_messages) do
      add :platform_user_id, :text, null: false
    end

    alter table(:livestream) do
      modify :started_at, :utc_datetime, null: true
    end
  end
end
