defmodule Streampai.Repo.Migrations.AddDonationPreferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_preferences) do
      add :min_donation_amount, :bigint
      add :max_donation_amount, :bigint
      add :donation_currency, :text, null: false, default: "USD"
    end
  end

  def down do
    alter table(:user_preferences) do
      remove :donation_currency
      remove :max_donation_amount
      remove :min_donation_amount
    end
  end
end
