defmodule Streampai.Repo.Migrations.AddLiveOutputsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cloudflare_live_outputs, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "cloudflare_live_outputs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :data, :map, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:cloudflare_live_outputs, "cloudflare_live_outputs_user_id_fkey")

    drop table(:cloudflare_live_outputs)
  end
end
