defmodule Streampai.Repo.Migrations.RemoveIdFromTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stream_donations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :decimal, null: false
      add :currency, :text, null: false, default: "USD"
      add :donor_name, :text, null: false
      add :message, :text
      add :platform, :text, null: false
      add :platform_donation_id, :text, null: false
      add :channel_id, :text, null: false
      add :donor_email, :text
      add :platform_metadata, :map, default: %{}
      add :featured, :boolean, default: false
      add :processed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "stream_donations_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:stream_donations, [:platform, :platform_donation_id],
             name: "stream_donations_unique_platform_donation_index"
           )

    create table(:raids, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :raider_channel_id, :text, null: false
      add :raider_username, :text, null: false
      add :target_channel_id, :text, null: false
      add :target_username, :text, null: false
      add :viewer_count, :bigint, null: false
      add :platform, :text, null: false
      add :platform_raid_id, :text
      add :message, :text
      add :platform_metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :raider_user_id,
          references(:users,
            column: :id,
            name: "raids_raider_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :target_user_id,
          references(:users,
            column: :id,
            name: "raids_target_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:patreons, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :patron_patreon_id, :text, null: false
      add :patron_name, :text, null: false
      add :patron_email, :text
      add :creator_patreon_id, :text, null: false
      add :pledge_amount, :decimal, null: false
      add :currency, :text, null: false, default: "USD"
      add :tier_id, :text
      add :tier_title, :text
      add :tier_description, :text
      add :status, :text, null: false, default: "active"
      add :patreon_pledge_id, :text, null: false
      add :patreon_campaign_id, :text, null: false
      add :pledge_created_at, :utc_datetime, null: false
      add :last_charge_date, :utc_datetime
      add :next_charge_date, :utc_datetime
      add :cancelled_at, :utc_datetime
      add :paused_at, :utc_datetime
      add :lifetime_support_cents, :bigint, null: false, default: 0
      add :pledge_relationship_start, :utc_datetime
      add :patreon_metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :patron_user_id,
          references(:users,
            column: :id,
            name: "patreons_patron_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :creator_user_id,
          references(:users,
            column: :id,
            name: "patreons_creator_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop constraint("tokens", "tokens_pkey")

    alter table(:tokens) do
      remove :id
    end

    create unique_index(:patreons, [:patreon_pledge_id],
             name: "patreons_unique_patreon_pledge_index"
           )

    create unique_index(:patreons, [:patron_patreon_id, :creator_patreon_id],
             name: "patreons_unique_patron_creator_index"
           )

    alter table(:chat_messages) do
      remove :emotes
      remove :badges
    end

    execute("ALTER TABLE \"tokens\" ADD PRIMARY KEY (jti)")
  end

  def down do
    alter table(:chat_messages) do
      add :badges, {:array, :text}, default: []
      add :emotes, :map, default: %{}
    end

    drop_if_exists unique_index(:patreons, [:patron_patreon_id, :creator_patreon_id],
                     name: "patreons_unique_patron_creator_index"
                   )

    drop_if_exists unique_index(:patreons, [:patreon_pledge_id],
                     name: "patreons_unique_patreon_pledge_index"
                   )

    alter table(:tokens) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()")
    end

    execute("ALTER TABLE \"tokens\" DROP constraint tokens_pkey")

    execute("ALTER TABLE \"tokens\" ADD PRIMARY KEY (id, jti)")

    drop constraint(:patreons, "patreons_patron_user_id_fkey")

    drop constraint(:patreons, "patreons_creator_user_id_fkey")

    drop table(:patreons)

    drop constraint(:raids, "raids_raider_user_id_fkey")

    drop constraint(:raids, "raids_target_user_id_fkey")

    drop table(:raids)

    drop_if_exists unique_index(:stream_donations, [:platform, :platform_donation_id],
                     name: "stream_donations_unique_platform_donation_index"
                   )

    drop constraint(:stream_donations, "stream_donations_user_id_fkey")

    drop table(:stream_donations)
  end
end
