defmodule Streampai.Repo.Migrations.Add do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:streaming_account, [:user_id, :platform],
             name: "streaming_account_unique_user_platform_index"
           )
  end

  def down do
    drop_if_exists unique_index(:streaming_account, [:user_id, :platform],
                     name: "streaming_account_unique_user_platform_index"
                   )
  end
end
