defmodule Streampai.Repo.Migrations.AddIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:user_premium_grants, [:stripe_subscription_id],
             name: "user_premium_grants_unique_stripe_subscription_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_premium_grants, [:stripe_subscription_id],
                     name: "user_premium_grants_unique_stripe_subscription_index"
                   )
  end
end
