defmodule Streampai.Repo.Migrations.Add do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:livestream, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :started_at, :utc_datetime
      add :ended_at, :utc_datetime
    end

    rename table(:chat_messages), :is_subscriber, to: :is_patreon

    alter table(:chat_messages) do
      add :livestream_id,
          references(:livestream,
            column: :id,
            name: "chat_messages_livestream_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:chat_messages, "chat_messages_livestream_id_fkey")

    alter table(:chat_messages) do
      remove :livestream_id
    end

    rename table(:chat_messages), :is_patreon, to: :is_subscriber

    drop table(:livestream)
  end
end
