defmodule Streampai.Repo.Migrations.AddRoleInvitationSystem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_roles) do
      add :role_status, :text, null: false, default: "pending"
      add :accepted_at, :utc_datetime_usec
    end

    drop_if_exists unique_index(:user_roles, [:user_id, :granter_id, :role_type],
                     name: "user_roles_unique_active_role_index"
                   )

    create unique_index(:user_roles, [:user_id, :granter_id, :role_type],
             name: "user_roles_unique_active_role_index",
             where: "(revoked_at IS NULL AND role_status = 'accepted')"
           )
  end

  def down do
    drop_if_exists unique_index(:user_roles, [:user_id, :granter_id, :role_type],
                     name: "user_roles_unique_active_role_index"
                   )

    create unique_index(:user_roles, [:user_id, :granter_id, :role_type],
             name: "user_roles_unique_active_role_index",
             where: "(revoked_at IS NULL)"
           )

    alter table(:user_roles) do
      remove :accepted_at
      remove :role_status
    end
  end
end
