defmodule Streampai.Repo.Migrations.MarkFieldsNotNulls do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_premium_grants) do
      modify :grant_reason, :text, null: false
      modify :expires_at, :utc_datetime, null: false
      modify :granted_by_user_id, :text, null: false

      modify :granted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:user_premium_grants) do
      modify :granted_at, :utc_datetime, null: true, default: nil
      modify :granted_by_user_id, :text, null: true
      modify :expires_at, :utc_datetime, null: true
      modify :grant_reason, :text, null: true
    end
  end
end
