defmodule Streampai.Repo.Migrations.RenameTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:livestreams, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :started_at, :utc_datetime, null: false
      add :ended_at, :utc_datetime
    end

    create table(:livestream_metrics, primary_key: false) do
      add :livestream_id, :uuid, null: false, primary_key: true
      add :youtube_viewers, :bigint, null: false, default: 0
      add :twitch_viewers, :bigint, null: false, default: 0

      add :created_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')"),
        primary_key: true
    end

    drop constraint(:chat_messages, "chat_messages_livestream_id_fkey")

    alter table(:chat_messages) do
      modify :livestream_id,
             references(:livestreams,
               column: :id,
               name: "chat_messages_livestream_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop table(:livestream)
    drop table(:livestream_metric)
  end

  def down do
    drop constraint(:chat_messages, "chat_messages_livestream_id_fkey")

    alter table(:chat_messages) do
      modify :livestream_id,
             references(:livestream,
               column: :id,
               name: "chat_messages_livestream_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop table(:livestream_metrics)

    drop table(:livestreams)
  end
end
