defmodule Streampai.Repo.Migrations.LimitLiveInputsToOnePerUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:cloudflare_live_inputs, [:user_id],
             name: "cloudflare_live_inputs_one_live_input_per_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:cloudflare_live_inputs, [:user_id],
                     name: "cloudflare_live_inputs_one_live_input_per_user_index"
                   )
  end
end
