defmodule Streampai.Repo.Migrations.GetRidOfChannelId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stream_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :data, :map, null: false
      add :data_raw, :map, null: false
      add :author_id, :text, null: false

      add :livestream_id,
          references(:livestreams,
            column: :id,
            name: "stream_events_livestream_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "stream_events_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :platform, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:stream_events, "stream_events_livestream_id_fkey")
    drop constraint(:stream_events, "stream_events_user_id_fkey")
    drop table(:stream_events)
  end
end
