defmodule Streampai.Repo.Migrations.AddChatMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:chat_messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :message, :text, null: false
      add :username, :text, null: false
      add :platform, :text, null: false
      add :platform_user_id, :text, null: false
      add :channel_id, :text, null: false
      add :is_moderator, :boolean, default: false
      add :is_subscriber, :boolean, default: false
      add :badges, {:array, :text}, default: []
      add :emotes, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "chat_messages_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:chat_messages, "chat_messages_user_id_fkey")

    drop table(:chat_messages)
  end
end
