defmodule Streampai.Repo.Migrations.AddUserPreferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_preferences, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "user_preferences_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :email_notifications, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:user_preferences, [:user_id], name: "user_preferences_primary_key_index")
  end

  def down do
    drop_if_exists unique_index(:user_preferences, [:user_id],
                     name: "user_preferences_primary_key_index"
                   )

    drop constraint(:user_preferences, "user_preferences_user_id_fkey")

    drop table(:user_preferences)
  end
end
