defmodule Streampai.Repo.Migrations.CreateFeatureFlags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:feature_flags, primary_key: false) do
      add :id, :text, null: false, primary_key: true
      add :enabled, :boolean, null: false, default: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:feature_flags, [:id], name: "feature_flags_unique_id_index")
  end

  def down do
    drop_if_exists unique_index(:feature_flags, [:id], name: "feature_flags_unique_id_index")

    drop table(:feature_flags)
  end
end