defmodule Streampai.Repo.Migrations.AddPremiumGrants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_premium_grants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :lock_in_amount, :bigint, null: false, default: 0

      add :initiated_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :type, :text, null: false, default: "purchase"
      add :granted_at, :utc_datetime
      add :granted_until, :date
      add :revoked_at, :utc_datetime

      add :user_id,
          references(:users,
            column: :id,
            name: "user_premium_grants_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:user_premium_grants, "user_premium_grants_user_id_fkey")

    drop table(:user_premium_grants)
  end
end
