defmodule Streampai.Repo.Migrations.Add2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:livestream_metric, primary_key: false) do
      add :livestream_id, :uuid, null: false, primary_key: true
      add :youtube_viewers, :bigint, null: false, default: 0
      add :twitch_viewers, :bigint, null: false, default: 0

      add :created_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')"),
        primary_key: true
    end

    alter table(:chat_messages) do
      modify :livestream_id, :uuid, null: false
      modify :user_id, :uuid, null: false
    end
  end

  def down do
    alter table(:chat_messages) do
      modify :user_id, :uuid, null: true
      modify :livestream_id, :uuid, null: true
    end

    drop table(:livestream_metric)
  end
end
