import Config

# Configure logger to handle more load and reduce sync/drop mode switching
config :logger, :default,
  level: :info,
  max_buffer_size: 10_000

# Do not print debug messages in production
config :logger, level: :info

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :streampai, StreampaiWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Streampai.Finch

# Storage settings will be configured in runtime.exs with environment variables

# Runtime production configuration, including reading

# Disable Swoosh Local Memory Storage
# of environment variables, is done on config/runtime.exs.
config :swoosh, local: false
