defmodule Streampai.Repo.Migrations.AddNotificationLocalizations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notification_localizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :notification_id,
          references(:notifications,
            column: :id,
            name: "notification_localizations_notification_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :locale, :text, null: false
      add :content, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:notification_localizations, [:notification_id, :locale],
             name: "notification_localizations_notification_locale_unique_index"
           )
  end

  def down do
    drop_if_exists unique_index(:notification_localizations, [:notification_id, :locale],
                     name: "notification_localizations_notification_locale_unique_index"
                   )

    drop constraint(
           :notification_localizations,
           "notification_localizations_notification_id_fkey"
         )

    drop table(:notification_localizations)
  end
end
