defmodule Streampai.Repo.Migrations.RenameThumbnailUrlToLegacy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:livestreams), :thumbnail_url, to: :legacy_thumbnail_url
  end

  def down do
    rename table(:livestreams), :legacy_thumbnail_url, to: :thumbnail_url
  end
end
