defmodule Streampai.Repo.Migrations.AddExtraDataToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :extra_data, :map, default: %{}
    end
  end

  def down do
    alter table(:users) do
      remove :extra_data
    end
  end
end
