defmodule Streampai.Repo.Migrations.CreateHighlightedMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:highlighted_messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :chat_message_id, :text, null: false
      add :message, :text, null: false
      add :sender_username, :text, null: false
      add :sender_channel_id, :text, null: false
      add :platform, :text, null: false
      add :viewer_id, :text

      add :highlighted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "highlighted_messages_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:highlighted_messages, [:user_id],
             name: "idx_highlighted_messages_user_id_unique",
             unique: true
           )

    create unique_index(:highlighted_messages, [:user_id], name: "highlighted_messages_unique_user_index")
  end

  def down do
    drop_if_exists unique_index(:highlighted_messages, [:user_id], name: "highlighted_messages_unique_user_index")

    drop constraint(:highlighted_messages, "highlighted_messages_user_id_fkey")

    drop_if_exists index(:highlighted_messages, [:user_id], name: "idx_highlighted_messages_user_id_unique")

    drop table(:highlighted_messages)
  end
end
