defmodule Streampai.Repo.Migrations.AddIftttWebhooks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ifttt_webhooks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :webhook_key, :text, null: false
      add :event_name_prefix, :text, null: false, default: "streampai"
      add :event_types, {:array, :text}, null: false
      add :is_enabled, :boolean, null: false, default: true
      add :last_tested_at, :utc_datetime_usec
      add :last_error, :text
      add :last_error_at, :utc_datetime_usec
      add :successful_deliveries, :bigint, null: false, default: 0
      add :failed_deliveries, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "ifttt_webhooks_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:ifttt_webhooks, [:is_enabled], name: "idx_ifttt_webhooks_enabled")

    create index(:ifttt_webhooks, [:user_id], name: "idx_ifttt_webhooks_user_id")

    create unique_index(:ifttt_webhooks, [:user_id, :name],
             name: "ifttt_webhooks_unique_user_ifttt_webhook_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:ifttt_webhooks, [:user_id, :name],
                     name: "ifttt_webhooks_unique_user_ifttt_webhook_name_index"
                   )

    drop constraint(:ifttt_webhooks, "ifttt_webhooks_user_id_fkey")

    drop_if_exists index(:ifttt_webhooks, [:user_id], name: "idx_ifttt_webhooks_user_id")

    drop_if_exists index(:ifttt_webhooks, [:is_enabled], name: "idx_ifttt_webhooks_enabled")

    drop table(:ifttt_webhooks)
  end
end
