defmodule Streampai.Repo.Migrations.AddThemePreference do
  @moduledoc """
  Adds theme_preference column to users table for storing user's preferred theme.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :theme_preference, :text
    end
  end

  def down do
    alter table(:users) do
      remove :theme_preference
    end
  end
end
