defmodule Streampai.Repo.Migrations.AddStreamTimers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stream_timers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :label, :text, null: false
      add :content, :text
      add :duration_seconds, :bigint, null: false
      add :remaining_seconds, :bigint, null: false, default: 0
      add :is_running, :boolean, null: false, default: false
      add :is_paused, :boolean, null: false, default: false
      add :started_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "stream_timers_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:stream_timers, [:user_id, :is_running], name: "idx_stream_timers_user_running")

    create index(:stream_timers, [:user_id], name: "idx_stream_timers_user_id")
  end

  def down do
    drop constraint(:stream_timers, "stream_timers_user_id_fkey")

    drop_if_exists index(:stream_timers, [:user_id], name: "idx_stream_timers_user_id")

    drop_if_exists index(:stream_timers, [:user_id, :is_running],
                     name: "idx_stream_timers_user_running"
                   )

    drop table(:stream_timers)
  end
end
