defmodule Streampai.Repo.Migrations.AddStreamSettingsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stream_settings, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "stream_settings_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :title, :text
      add :description, :text
      add :thumbnail_url, :text
      add :tags, {:array, :text}, default: []
      add :visibility, :text, null: false, default: "public"
      add :enabled_platforms, {:array, :text}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:stream_settings, [:user_id],
             name: "stream_settings_unique_user_settings_index"
           )
  end

  def down do
    drop_if_exists unique_index(:stream_settings, [:user_id],
                     name: "stream_settings_unique_user_settings_index"
                   )

    drop constraint(:stream_settings, "stream_settings_user_id_fkey")

    drop table(:stream_settings)
  end
end
