defmodule Streampai.Repo.Migrations.AddNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "notifications_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :content, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:notification_reads, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "notification_reads_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :notification_id,
          references(:notifications,
            column: :id,
            name: "notification_reads_notification_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :seen_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:notification_reads, [:user_id, :notification_id],
             name: "notification_reads_user_notification_unique_index"
           )
  end

  def down do
    drop_if_exists unique_index(:notification_reads, [:user_id, :notification_id],
                     name: "notification_reads_user_notification_unique_index"
                   )

    drop constraint(:notification_reads, "notification_reads_user_id_fkey")

    drop constraint(:notification_reads, "notification_reads_notification_id_fkey")

    drop table(:notification_reads)

    drop constraint(:notifications, "notifications_user_id_fkey")

    drop table(:notifications)
  end
end
