defmodule Streampai.Repo.Migrations.SyncThemePreference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  # Column already exists from migration 20251228150000_add_theme_preference
  # This migration syncs the Ash snapshot only
  def up do
  end

  def down do
  end
end
