defmodule Streampai.Repo.Migrations.AddWidgetConfigTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:widget_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "widget_configs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :type, :text, null: false
      add :config, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:widget_configs, [:user_id, :type],
             name: "widget_configs_user_type_unique_index"
           )
  end

  def down do
    drop_if_exists unique_index(:widget_configs, [:user_id, :type],
                     name: "widget_configs_user_type_unique_index"
                   )

    drop constraint(:widget_configs, "widget_configs_user_id_fkey")

    drop table(:widget_configs)
  end
end
