defmodule Streampai.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute(
      "ALTER INDEX cloudflare_live_inputs_one_live_input_per_user_orientation_index RENAME TO cf_live_inputs_user_orientation_idx"
    )
  end

  def down do
    execute(
      "ALTER INDEX cf_live_inputs_user_orientation_idx RENAME TO cloudflare_live_inputs_one_live_input_per_user_orientation_index"
    )
  end
end
