defmodule Streampai.Repo.Migrations.FixActorStateIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:actor_states, [:type], name: "idx_actor_states_type")

    drop_if_exists index(:actor_states, [:type, :user_id], name: "idx_actor_states_type_user")

    drop_if_exists unique_index(:actor_states, [:type, :user_id],
                     name: "actor_states_unique_type_user_index"
                   )

    create unique_index(:actor_states, [:type, :user_id],
             name: "actor_states_unique_type_user_index",
             nulls_distinct: false
           )
  end

  def down do
    drop_if_exists unique_index(:actor_states, [:type, :user_id],
                     name: "actor_states_unique_type_user_index"
                   )

    create unique_index(:actor_states, [:type, :user_id],
             name: "actor_states_unique_type_user_index"
           )

    create index(:actor_states, [:type, :user_id],
             name: "idx_actor_states_type_user",
             unique: true,
             where: "user_id IS NOT NULL"
           )

    create index(:actor_states, [:type], name: "idx_actor_states_type", where: "user_id IS NULL")
  end
end
