defmodule Streampai.Repo.Migrations.AddViewerCols do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stream_viewers) do
      add :avatar_url, :text
      add :channel_url, :text
      add :is_verified, :boolean, default: false
      add :is_owner, :boolean, default: false
      add :is_moderator, :boolean, default: false
      add :is_patreon, :boolean, default: false
    end
  end

  def down do
    alter table(:stream_viewers) do
      remove :is_patreon
      remove :is_moderator
      remove :is_owner
      remove :is_verified
      remove :channel_url
      remove :avatar_url
    end
  end
end
