defmodule Streampai.Repo.Migrations.FixStreamingAccountUserIdType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Change the column type first
    execute("ALTER TABLE streaming_account ALTER COLUMN user_id TYPE uuid USING user_id::uuid")

    # Add the foreign key constraint
    execute(
      "ALTER TABLE streaming_account ADD CONSTRAINT streaming_account_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)"
    )

    create index(:streaming_account, [:user_id])
  end

  def down do
    drop_if_exists index(:streaming_account, [:user_id])

    drop constraint(:streaming_account, "streaming_account_user_id_fkey")

    alter table(:streaming_account) do
      modify :user_id, :text
    end
  end
end
