defmodule Streampai.Repo.Migrations.AddSimplifiedViewerSystem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:viewers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:users) do
      add :avatar, :text
    end

    create table(:stream_viewers, primary_key: false) do
      add :viewer_id,
          references(:viewers,
            column: :id,
            name: "stream_viewers_viewer_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "stream_viewers_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :display_name, :text, null: false
      add :notes, :text
      add :ai_summary, :text

      add :first_seen_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :last_seen_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute "CREATE INDEX idx_stream_viewers_display_name_gin ON stream_viewers USING gin (display_name gin_trgm_ops)"

    create index(:stream_viewers, [:user_id, :last_seen_at],
             name: "idx_stream_viewers_user_last_seen"
           )

    create index(:stream_viewers, [:user_id, :display_name],
             name: "idx_stream_viewers_user_display_name"
           )

    create unique_index(:stream_viewers, [:viewer_id, :user_id],
             name: "stream_viewers_primary_key_index"
           )

    alter table(:stream_events) do
      add :viewer_id,
          references(:viewers,
            column: :id,
            name: "stream_events_viewer_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:stream_events, [:viewer_id, :inserted_at],
             name: "idx_stream_events_viewer_chrono"
           )

    alter table(:chat_messages) do
      remove :updated_at
      remove :is_patreon
      remove :is_moderator
      remove :channel_id
      remove :username
      modify :id, :text, default: nil
      add :sender_username, :text, null: false
      add :sender_channel_id, :text, null: false
      add :sender_is_moderator, :boolean, default: false
      add :sender_is_patreon, :boolean, default: false

      add :viewer_id,
          references(:viewers,
            column: :id,
            name: "chat_messages_viewer_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:chat_messages, [:livestream_id, :inserted_at],
             name: "idx_chat_messages_stream_chrono"
           )

    create index(:chat_messages, [:inserted_at], name: "idx_chat_messages_inserted_at")

    create index(:chat_messages, [:livestream_id], name: "idx_chat_messages_livestream_id")

    create index(:chat_messages, [:user_id], name: "idx_chat_messages_user_id")

    create unique_index(:chat_messages, [:id], name: "chat_messages_primary_key_index")
  end

  def down do
    drop_if_exists unique_index(:chat_messages, [:id], name: "chat_messages_primary_key_index")

    drop constraint(:chat_messages, "chat_messages_viewer_id_fkey")

    drop_if_exists index(:chat_messages, [:user_id], name: "idx_chat_messages_user_id")

    drop_if_exists index(:chat_messages, [:livestream_id],
                     name: "idx_chat_messages_livestream_id"
                   )

    drop_if_exists index(:chat_messages, [:inserted_at], name: "idx_chat_messages_inserted_at")

    drop_if_exists index(:chat_messages, [:livestream_id, :inserted_at],
                     name: "idx_chat_messages_stream_chrono"
                   )

    alter table(:chat_messages) do
      remove :viewer_id
      remove :sender_is_patreon
      remove :sender_is_moderator
      remove :sender_channel_id
      remove :sender_username
      modify :id, :uuid, default: fragment("gen_random_uuid()")
      add :username, :text, null: false
      add :channel_id, :text, null: false
      add :is_moderator, :boolean, default: false
      add :is_patreon, :boolean, default: false

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    drop constraint(:stream_events, "stream_events_viewer_id_fkey")

    drop_if_exists index(:stream_events, [:viewer_id, :inserted_at],
                     name: "idx_stream_events_viewer_chrono"
                   )

    alter table(:stream_events) do
      remove :viewer_id
    end

    drop_if_exists unique_index(:stream_viewers, [:viewer_id, :user_id],
                     name: "stream_viewers_primary_key_index"
                   )

    drop constraint(:stream_viewers, "stream_viewers_viewer_id_fkey")

    drop constraint(:stream_viewers, "stream_viewers_user_id_fkey")

    drop_if_exists index(:stream_viewers, [:user_id, :display_name],
                     name: "idx_stream_viewers_user_display_name"
                   )

    drop_if_exists index(:stream_viewers, [:user_id, :last_seen_at],
                     name: "idx_stream_viewers_user_last_seen"
                   )

    execute "DROP INDEX IF EXISTS idx_stream_viewers_display_name_gin"

    drop table(:stream_viewers)

    alter table(:users) do
      remove :avatar
    end

    drop table(:viewers)
  end
end
