defmodule Streampai.Repo.Migrations.AddNewsletterTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:newsletter_emails, primary_key: false) do
      add :email, :text, null: false, primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:newsletter_emails, [:email],
             name: "newsletter_emails_unique_email_index"
           )
  end

  def down do
    drop_if_exists unique_index(:newsletter_emails, [:email],
                     name: "newsletter_emails_unique_email_index"
                   )

    drop table(:newsletter_emails)
  end
end
