defmodule Streampai.Repo.Migrations.AddThumbnailFileToLivestreams do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:livestreams) do
      add :thumbnail_file_id,
          references(:files,
            column: :id,
            name: "livestreams_thumbnail_file_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:livestreams, "livestreams_thumbnail_file_id_fkey")

    alter table(:livestreams) do
      remove :thumbnail_file_id
    end
  end
end
