defmodule Streampai.Repo.Migrations.UpdateStreamTimersSimplified do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:stream_timers, [:user_id, :is_running], name: "idx_stream_timers_user_running")

    alter table(:stream_timers) do
      remove :started_at
      remove :is_paused
      remove :is_running
      remove :remaining_seconds
      remove :duration_seconds
      modify :content, :text, null: false
      add :interval_seconds, :bigint, null: false
      add :is_active, :boolean, null: false, default: false
      add :next_fire_at, :utc_datetime_usec
    end

    create index(:stream_timers, [:is_active, :next_fire_at], name: "idx_stream_timers_active_next_fire")

    create index(:stream_timers, [:user_id, :is_active], name: "idx_stream_timers_user_active")
  end

  def down do
    drop_if_exists index(:stream_timers, [:user_id, :is_active], name: "idx_stream_timers_user_active")

    drop_if_exists index(:stream_timers, [:is_active, :next_fire_at], name: "idx_stream_timers_active_next_fire")

    alter table(:stream_timers) do
      remove :next_fire_at
      remove :is_active
      remove :interval_seconds
      modify :content, :text, null: true
      add :duration_seconds, :bigint, null: false
      add :remaining_seconds, :bigint, null: false, default: 0
      add :is_running, :boolean, null: false, default: false
      add :is_paused, :boolean, null: false, default: false
      add :started_at, :utc_datetime_usec
    end

    create index(:stream_timers, [:user_id, :is_running], name: "idx_stream_timers_user_running")
  end
end
