defmodule Streampai.Repo.Migrations.AddLivestreamColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:livestreams) do
      add_if_not_exists :category, :text
      add_if_not_exists :subcategory, :text
      add_if_not_exists :language, :text
      add_if_not_exists :tags, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:livestreams) do
      remove :tags
      remove :language
      remove :subcategory
      remove :category
    end
  end
end
