defmodule Streampai.Repo.Migrations.AddStreamMetadataFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:livestreams) do
      add :title, :text, null: false, default: "Untitled Stream"
      add :thumbnail_url, :text
    end

    alter table(:livestreams) do
      modify :title, :text, null: false, default: nil
    end
  end

  def down do
    alter table(:livestreams) do
      remove :thumbnail_url
      remove :title
    end
  end
end
