defmodule Streampai.Repo.Migrations.AddContentHashToFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:files) do
      add :content_hash, :text
    end

    create unique_index(:files, [:content_hash, :file_type], name: "files_content_hash_index")
  end

  def down do
    drop_if_exists unique_index(:files, [:content_hash, :file_type],
                     name: "files_content_hash_index"
                   )

    alter table(:files) do
      remove :content_hash
    end
  end
end
