defmodule Streampai.Repo.Migrations.AddAvatarFileToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :avatar

      add :avatar_file_id,
          references(:files,
            column: :id,
            name: "users_avatar_file_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:users, "users_avatar_file_id_fkey")

    alter table(:users) do
      remove :avatar_file_id
      add :avatar, :text
    end
  end
end
