defmodule Streampai.Repo.Migrations.AllowNilPlatformInStreamEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stream_events) do
      modify :platform, :text, null: true
    end
  end

  def down do
    alter table(:stream_events) do
      modify :platform, :text, null: false
    end
  end
end
