defmodule Streampai.Repo.Migrations.Chore do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Table already exists from rename migration, just ensure index exists
    # Drop old index name if it exists
    drop_if_exists unique_index(:smart_canvas_layouts, [:user_id],
                     name: "smart_widget_layouts_user_unique_index"
                   )

    # Create new index with correct name
    create_if_not_exists unique_index(:smart_canvas_layouts, [:user_id],
                           name: "smart_canvas_layouts_user_unique_index"
                         )
  end

  def down do
    # Restore old index name
    drop_if_exists unique_index(:smart_canvas_layouts, [:user_id],
                     name: "smart_canvas_layouts_user_unique_index"
                   )

    create_if_not_exists unique_index(:smart_canvas_layouts, [:user_id],
                           name: "smart_widget_layouts_user_unique_index"
                         )
  end
end
