defmodule Streampai.Repo.Migrations.AddUniqueViewersLast30d do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:streaming_account) do
      remove :subscriber_count
      add :unique_viewers_last_30d, :bigint
    end
  end

  def down do
    alter table(:streaming_account) do
      remove :unique_viewers_last_30d
      add :subscriber_count, :bigint
    end
  end
end
