defmodule Streampai.Repo.Migrations.AddDiscordActors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:discord_actors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :bot_token, :text, null: false
      add :bot_name, :text
      add :status, :text, null: false, default: "disconnected"
      add :event_types, {:array, :text}, null: false, default: ["donation", "stream_start", "stream_end"]
      add :announcement_guild_id, :text
      add :announcement_channel_id, :text
      add :actor_state, :map, null: false, default: %{}
      add :last_connected_at, :utc_datetime_usec
      add :last_synced_at, :utc_datetime_usec
      add :last_error, :text
      add :last_error_at, :utc_datetime_usec
      add :messages_sent, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "discord_actors_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:discord_actors, [:status], name: "idx_discord_actors_status")

    create index(:discord_actors, [:user_id], name: "idx_discord_actors_user_id")

    create unique_index(:discord_actors, [:user_id],
             name: "discord_actors_unique_user_actor_index"
           )
  end

  def down do
    drop_if_exists unique_index(:discord_actors, [:user_id],
                     name: "discord_actors_unique_user_actor_index"
                   )

    drop constraint(:discord_actors, "discord_actors_user_id_fkey")

    drop_if_exists index(:discord_actors, [:user_id], name: "idx_discord_actors_user_id")

    drop_if_exists index(:discord_actors, [:status], name: "idx_discord_actors_status")

    drop table(:discord_actors)
  end
end
