defmodule Streampai.Repo.Migrations.AddFilesTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:files, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :storage_key, :text, null: false
      add :filename, :text, null: false
      add :content_type, :text, null: false, default: "application/octet-stream"
      add :size_bytes, :bigint
      add :status, :text, null: false, default: "pending"
      add :file_type, :text, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "files_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :deleted_at, :utc_datetime
    end

    create unique_index(:files, [:storage_key], name: "files_unique_storage_key_index")
  end

  def down do
    drop_if_exists unique_index(:files, [:storage_key], name: "files_unique_storage_key_index")

    drop constraint(:files, "files_user_id_fkey")

    drop table(:files)
  end
end
