defmodule Streampai.Repo.Migrations.AddActorState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:actor_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :data, :map, null: false, default: %{}
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "actor_states_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:actor_states, [:status], name: "idx_actor_states_status")

    create index(:actor_states, [:type], name: "idx_actor_states_type", where: "user_id IS NULL")

    create index(:actor_states, [:type, :user_id],
             name: "idx_actor_states_type_user",
             unique: true,
             where: "user_id IS NOT NULL"
           )

    create unique_index(:actor_states, [:type, :user_id],
             name: "actor_states_unique_type_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:actor_states, [:type, :user_id],
                     name: "actor_states_unique_type_user_index"
                   )

    drop constraint(:actor_states, "actor_states_user_id_fkey")

    drop_if_exists index(:actor_states, [:type, :user_id], name: "idx_actor_states_type_user")

    drop_if_exists index(:actor_states, [:type], name: "idx_actor_states_type")

    drop_if_exists index(:actor_states, [:status], name: "idx_actor_states_status")

    drop table(:actor_states)
  end
end
