defmodule Streampai.Repo.Migrations.AddMetricsForMorePlatforms do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:livestream_metrics) do
      add :facebook_viewers, :bigint, null: false, default: 0
      add :kick_viewers, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:livestream_metrics) do
      remove :kick_viewers
      remove :facebook_viewers
    end
  end
end
