defmodule Streampai.Repo.Migrations.AddDefaultVoicePreference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_preferences) do
      add :default_voice, :text
    end
  end

  def down do
    alter table(:user_preferences) do
      remove :default_voice
    end
  end
end
