defmodule Streampai.Repo.Migrations.AddLanguagePreference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :language_preference, :text
    end
  end

  def down do
    alter table(:users) do
      remove :language_preference
    end
  end
end
