defmodule Streampai.Repo.Migrations.AddChatTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create_if_not_exists unique_index(:chat_messages, [:livestream_id, :username, :message],
             name: "chat_messages_unique_message_per_stream_index"
           )
  end

  def down do
    drop_if_exists unique_index(:chat_messages, [:livestream_id, :username, :message],
                     name: "chat_messages_unique_message_per_stream_index"
                   )
  end
end
