defmodule Streampai.Repo.Migrations.SmartWidgetLayout do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:smart_widget_layouts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "smart_widget_layouts_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :widgets, {:array, :map}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:smart_widget_layouts, [:user_id],
             name: "smart_widget_layouts_user_unique_index"
           )
  end

  def down do
    drop_if_exists unique_index(:smart_widget_layouts, [:user_id],
                     name: "smart_widget_layouts_user_unique_index"
                   )

    drop constraint(:smart_widget_layouts, "smart_widget_layouts_user_id_fkey")

    drop table(:smart_widget_layouts)
  end
end
