defmodule Streampai.Repo.Migrations.AddPlatformToStreamViewers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stream_viewers) do
      add :platform, :text, null: true
    end

    # Set default platform for existing records
    execute "UPDATE stream_viewers SET platform = 'twitch' WHERE platform IS NULL"

    # Now make it non-nullable
    alter table(:stream_viewers) do
      modify :platform, :text, null: false
    end
  end

  def down do
    alter table(:stream_viewers) do
      remove :platform
    end
  end
end
