defmodule Streampai.Repo.Migrations.GenerateStreamEventIdenitites do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:stream_events, [:id], name: "stream_events_primary_key_index")
  end

  def down do
    drop_if_exists unique_index(:stream_events, [:id], name: "stream_events_primary_key_index")
  end
end
