defmodule Streampai.Repo.Migrations.RemoveRedundantChatMesssages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stream_events) do
      modify :data, :map, default: nil
    end
  end

  def down do
    alter table(:stream_events) do
      modify :data, :map, default: %{}
    end
  end
end
