defmodule Streampai.Repo.Migrations.AddBannedByUserId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:banned_viewers) do
      add :banned_by_user_id,
          references(:users,
            column: :id,
            name: "banned_viewers_banned_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:banned_viewers, "banned_viewers_banned_by_user_id_fkey")

    alter table(:banned_viewers) do
      remove :banned_by_user_id
    end
  end
end
