defmodule Streampai.Repo.Migrations.AddStripeFieldsToUserPremiumGrants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_premium_grants) do
      add :stripe_subscription_id, :text
      add :granted_by_user_id, :text
      add :expires_at, :utc_datetime
      add :grant_reason, :text
      add :metadata, :map, default: %{}
    end
  end

  def down do
    alter table(:user_premium_grants) do
      remove :metadata
      remove :grant_reason
      remove :expires_at
      remove :granted_by_user_id
      remove :stripe_subscription_id
    end
  end
end
