defmodule Streampai.Repo.Migrations.AddStreamingAccountStats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:streaming_account) do
      add :sponsor_count, :bigint
      add :views_last_30d, :bigint
      add :follower_count, :bigint
      add :subscriber_count, :bigint
      add :stats_last_refreshed_at, :utc_datetime
    end
  end

  def down do
    alter table(:streaming_account) do
      remove :stats_last_refreshed_at
      remove :subscriber_count
      remove :follower_count
      remove :views_last_30d
      remove :sponsor_count
    end
  end
end
