defmodule Streampai.Repo.Migrations.AddAiChatConfigFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:chat_bot_configs) do
      add :ai_personality, :text
      add :ai_bot_name, :text, null: false, default: "Streampai"
      add :ai_provider, :text, null: false, default: "openai"
    end
  end

  def down do
    alter table(:chat_bot_configs) do
      remove :ai_provider
      remove :ai_bot_name
      remove :ai_personality
    end
  end
end
