defmodule Streampai.Repo.Migrations.AddMembraneLiveInputs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:membrane_live_inputs, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "membrane_live_inputs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false

      add :orientation, :text, null: false, default: "horizontal", primary_key: true
      add :stream_key, :text, null: false
      add :data, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:membrane_live_inputs, [:user_id, :orientation],
             name: "membrane_live_inputs_one_per_user_orientation_index"
           )
  end

  def down do
    drop_if_exists unique_index(:membrane_live_inputs, [:user_id, :orientation],
                     name: "membrane_live_inputs_one_per_user_orientation_index"
                   )

    drop constraint(:membrane_live_inputs, "membrane_live_inputs_user_id_fkey")

    drop table(:membrane_live_inputs)
  end
end
