defmodule Streampai.Repo.Migrations.CurrentStreamData do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:current_stream_data, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "idle"
      add :stream_data, :map, null: false, default: %{}
      add :cloudflare_data, :map, null: false, default: %{}
      add :youtube_data, :map, null: false, default: %{}
      add :twitch_data, :map, null: false, default: %{}
      add :kick_data, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "current_stream_data_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:current_stream_data, [:user_id],
             name: "current_stream_data_unique_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:current_stream_data, [:user_id],
                     name: "current_stream_data_unique_user_index"
                   )

    drop constraint(:current_stream_data, "current_stream_data_user_id_fkey")

    drop table(:current_stream_data)
  end
end
