defmodule Streampai.Repo.Migrations.T do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Already handled by 20260130110058_rename_legacy_thumbnail_url_back
  end

  def down do
  end
end
