defmodule Streampai.Repo.Migrations.AddBitrateToLivestreamMetrics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:livestream_metrics) do
      add :input_bitrate_kbps, :bigint
    end
  end

  def down do
    alter table(:livestream_metrics) do
      remove :input_bitrate_kbps
    end
  end
end
