defmodule Streampai.Repo.Migrations.AddAlertboxStateToCurrentStreamData do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:current_stream_data) do
      add :alertbox_state, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:current_stream_data) do
      remove :alertbox_state
    end
  end
end
