defmodule Streampai.Repo.Migrations.AddPaddleSubscriptionId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_premium_grants) do
      add :paddle_subscription_id, :text
    end

    create unique_index(:user_premium_grants, [:paddle_subscription_id],
             name: "user_premium_grants_unique_paddle_subscription_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_premium_grants, [:paddle_subscription_id],
                     name: "user_premium_grants_unique_paddle_subscription_index"
                   )

    alter table(:user_premium_grants) do
      remove :paddle_subscription_id
    end
  end
end
