defmodule Streampai.Repo.Migrations.AddStreamingAccountStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:streaming_account) do
      add :status, :text, null: false, default: "connected"
    end
  end

  def down do
    alter table(:streaming_account) do
      remove :status
    end
  end
end
