defmodule Streampai.Repo.Migrations.AddChatBotConfig do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:chat_bot_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :enabled, :boolean, null: false, default: true
      add :greeting_enabled, :boolean, null: false, default: false
      add :greeting_message, :text, null: false, default: "Hello everyone! Welcome to the stream!"
      add :command_prefix, :text, null: false, default: "/"
      add :auto_shoutout_enabled, :boolean, null: false, default: false
      add :link_protection_enabled, :boolean, null: false, default: false
      add :slow_mode_on_raid_enabled, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "chat_bot_configs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:chat_bot_configs, [:user_id],
             name: "idx_chat_bot_configs_user_id",
             unique: true
           )

    create unique_index(:chat_bot_configs, [:user_id], name: "chat_bot_configs_unique_user_index")
  end

  def down do
    drop_if_exists unique_index(:chat_bot_configs, [:user_id],
                     name: "chat_bot_configs_unique_user_index"
                   )

    drop constraint(:chat_bot_configs, "chat_bot_configs_user_id_fkey")

    drop_if_exists index(:chat_bot_configs, [:user_id], name: "idx_chat_bot_configs_user_id")

    drop table(:chat_bot_configs)
  end
end
