defmodule Streampai.Repo.Migrations.AddAlertAndHighlightToCurrentStreamData do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:current_stream_data) do
      add :active_alert, :map
      add :highlighted_message, :map
    end
  end

  def down do
    alter table(:current_stream_data) do
      remove :highlighted_message
      remove :active_alert
    end
  end
end
