defmodule Streampai.Repo.Migrations.ReplaceTimerActiveWithDisabledAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:stream_timers, [:is_active, :next_fire_at],
                     name: "idx_stream_timers_active_next_fire"
                   )

    drop_if_exists index(:stream_timers, [:user_id, :is_active],
                     name: "idx_stream_timers_user_active"
                   )

    alter table(:stream_timers) do
      remove :next_fire_at
      remove :is_active
      add :disabled_at, :utc_datetime_usec
    end

    create index(:stream_timers, [:user_id, :disabled_at],
             name: "idx_stream_timers_user_disabled"
           )
  end

  def down do
    drop_if_exists index(:stream_timers, [:user_id, :disabled_at],
                     name: "idx_stream_timers_user_disabled"
                   )

    alter table(:stream_timers) do
      remove :disabled_at
      add :is_active, :boolean, null: false, default: false
      add :next_fire_at, :utc_datetime_usec
    end

    create index(:stream_timers, [:user_id, :is_active], name: "idx_stream_timers_user_active")

    create index(:stream_timers, [:is_active, :next_fire_at],
             name: "idx_stream_timers_active_next_fire"
           )
  end
end
