defmodule Streampai.Repo.Migrations.AddCreemAndDodoSubscriptionIds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_premium_grants) do
      add :dodo_subscription_id, :text
      add :creem_subscription_id, :text
    end

    create unique_index(:user_premium_grants, [:creem_subscription_id],
             name: "user_premium_grants_unique_creem_subscription_index"
           )

    create unique_index(:user_premium_grants, [:dodo_subscription_id],
             name: "user_premium_grants_unique_dodo_subscription_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_premium_grants, [:dodo_subscription_id],
                     name: "user_premium_grants_unique_dodo_subscription_index"
                   )

    drop_if_exists unique_index(:user_premium_grants, [:creem_subscription_id],
                     name: "user_premium_grants_unique_creem_subscription_index"
                   )

    alter table(:user_premium_grants) do
      remove :creem_subscription_id
      remove :dodo_subscription_id
    end
  end
end
