defmodule Streampai.Repo.Migrations.EncryptOauthTokens do
  @moduledoc """
  Adds encrypted token columns for OAuth tokens.

  Existing plaintext tokens are dropped since they need to be re-encrypted
  with the new Vault key. Users will need to reconnect their streaming accounts
  after this migration.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:streaming_account) do
      remove :access_token
      remove :refresh_token
      add :encrypted_access_token, :binary, null: false, default: ""
      add :encrypted_refresh_token, :binary, null: false, default: ""
    end

    alter table(:paypal_connections) do
      remove :refresh_token
      remove :access_token
      add :encrypted_access_token, :binary
      add :encrypted_refresh_token, :binary
    end
  end

  def down do
    alter table(:paypal_connections) do
      remove :encrypted_refresh_token
      remove :encrypted_access_token
      add :access_token, :text
      add :refresh_token, :text
    end

    alter table(:streaming_account) do
      remove :encrypted_refresh_token
      remove :encrypted_access_token
      add :refresh_token, :text, null: false
      add :access_token, :text, null: false
    end
  end
end
