defmodule Streampai.Repo.Migrations.RemoveDataRawAndChatMessage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stream_events) do
      remove :data_raw
    end
  end

  def down do
    alter table(:stream_events) do
      add :data_raw, :map, null: false
    end
  end
end
