defmodule Streampai.Repo.Migrations.UpdateChatbotCommandPrefixDefault do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:chat_bot_configs) do
      modify :command_prefix, :text, default: "!"
    end
  end

  def down do
    alter table(:chat_bot_configs) do
      modify :command_prefix, :text, default: "/"
    end
  end
end
