defmodule Streampai.Repo.Migrations.AddAiChatEnabled do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:chat_bot_configs) do
      add :ai_chat_enabled, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:chat_bot_configs) do
      remove :ai_chat_enabled
    end
  end
end
