defmodule Streampai.Repo.Migrations.AddStreamHooks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stream_hooks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :enabled, :boolean, null: false, default: true
      add :trigger_type, :text, null: false
      add :conditions, :map, default: %{}
      add :action_type, :text, null: false
      add :action_config, :map, null: false
      add :cooldown_seconds, :bigint, null: false, default: 0
      add :last_triggered_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "stream_hooks_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:stream_hooks, [:user_id, :trigger_type], name: "idx_stream_hooks_user_trigger")

    create index(:stream_hooks, [:user_id, :enabled], name: "idx_stream_hooks_user_enabled")

    create index(:stream_hooks, [:user_id], name: "idx_stream_hooks_user_id")

    create table(:stream_hook_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :hook_id,
          references(:stream_hooks,
            column: :id,
            name: "stream_hook_logs_hook_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "stream_hook_logs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :stream_event_id, :uuid
      add :trigger_type, :text, null: false
      add :action_type, :text, null: false
      add :status, :text, null: false
      add :error_message, :text
      add :executed_at, :utc_datetime_usec, null: false
      add :duration_ms, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:stream_hook_logs, [:hook_id, :inserted_at],
             name: "idx_stream_hook_logs_hook_chrono"
           )

    create index(:stream_hook_logs, [:user_id, :inserted_at],
             name: "idx_stream_hook_logs_user_chrono"
           )
  end

  def down do
    drop constraint(:stream_hook_logs, "stream_hook_logs_hook_id_fkey")

    drop constraint(:stream_hook_logs, "stream_hook_logs_user_id_fkey")

    drop_if_exists index(:stream_hook_logs, [:user_id, :inserted_at],
                     name: "idx_stream_hook_logs_user_chrono"
                   )

    drop_if_exists index(:stream_hook_logs, [:hook_id, :inserted_at],
                     name: "idx_stream_hook_logs_hook_chrono"
                   )

    drop table(:stream_hook_logs)

    drop constraint(:stream_hooks, "stream_hooks_user_id_fkey")

    drop_if_exists index(:stream_hooks, [:user_id], name: "idx_stream_hooks_user_id")

    drop_if_exists index(:stream_hooks, [:user_id, :enabled],
                     name: "idx_stream_hooks_user_enabled"
                   )

    drop_if_exists index(:stream_hooks, [:user_id, :trigger_type],
                     name: "idx_stream_hooks_user_trigger"
                   )

    drop table(:stream_hooks)
  end
end
