defmodule Streampai.Repo.Migrations.AddStreamStateEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stream_state_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :livestream_id,
          references(:livestreams,
            column: :id,
            name: "stream_state_events_livestream_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "stream_state_events_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :event_type, :text, null: false
      add :from_state, :text
      add :to_state, :text, null: false
      add :event_data, :map, null: false, default: %{}
      add :timestamp, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:stream_state_events, [:user_id, :inserted_at],
             name: "idx_stream_state_events_user_chrono"
           )

    create index(:stream_state_events, [:livestream_id, :inserted_at],
             name: "idx_stream_state_events_livestream_chrono"
           )
  end

  def down do
    drop constraint(:stream_state_events, "stream_state_events_livestream_id_fkey")

    drop constraint(:stream_state_events, "stream_state_events_user_id_fkey")

    drop_if_exists index(:stream_state_events, [:livestream_id, :inserted_at],
                     name: "idx_stream_state_events_livestream_chrono"
                   )

    drop_if_exists index(:stream_state_events, [:user_id, :inserted_at],
                     name: "idx_stream_state_events_user_chrono"
                   )

    drop table(:stream_state_events)
  end
end
