defmodule Streampai.Repo.Migrations.FlipWasDisplayedDefault do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stream_events) do
      modify :was_displayed, :boolean, default: false
    end
  end

  def down do
    alter table(:stream_events) do
      modify :was_displayed, :boolean, default: true
    end
  end
end
