/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as DashboardStreamRouteImport } from './routes/dashboard/stream'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardChatHistoryRouteImport } from './routes/dashboard/chat-history'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardWidgetsIndexRouteImport } from './routes/dashboard/widgets/index'
import { Route as DashboardViewersIndexRouteImport } from './routes/dashboard/viewers/index'
import { Route as DashboardStreamHistoryIndexRouteImport } from './routes/dashboard/stream-history/index'
import { Route as DashboardScenesIndexRouteImport } from './routes/dashboard/scenes/index'
import { Route as WidgetsViewerCountObsRouteImport } from './routes/widgets/viewer-count/obs'
import { Route as WidgetsTopDonorsObsRouteImport } from './routes/widgets/top-donors/obs'
import { Route as WidgetsPollObsRouteImport } from './routes/widgets/poll/obs'
import { Route as WidgetsFollowerCountObsRouteImport } from './routes/widgets/follower-count/obs'
import { Route as WidgetsEventListObsRouteImport } from './routes/widgets/event-list/obs'
import { Route as WidgetsDonationGoalObsRouteImport } from './routes/widgets/donation-goal/obs'
import { Route as WidgetsChatObsRouteImport } from './routes/widgets/chat/obs'
import { Route as WidgetsAlertboxObsRouteImport } from './routes/widgets/alertbox/obs'
import { Route as WViewerCountUserIdRouteImport } from './routes/w/viewer-count/$userId'
import { Route as WTopdonorsUserIdRouteImport } from './routes/w/topdonors/$userId'
import { Route as WTimerUserIdRouteImport } from './routes/w/timer/$userId'
import { Route as WSmartCanvasUserIdRouteImport } from './routes/w/smart-canvas/$userId'
import { Route as WSliderUserIdRouteImport } from './routes/w/slider/$userId'
import { Route as WPollUserIdRouteImport } from './routes/w/poll/$userId'
import { Route as WPlaceholderUserIdRouteImport } from './routes/w/placeholder/$userId'
import { Route as WMessageHighlightUserIdRouteImport } from './routes/w/message-highlight/$userId'
import { Route as WGiveawayUserIdRouteImport } from './routes/w/giveaway/$userId'
import { Route as WFollowerCountUserIdRouteImport } from './routes/w/follower-count/$userId'
import { Route as WEventlistUserIdRouteImport } from './routes/w/eventlist/$userId'
import { Route as WDonationGoalUserIdRouteImport } from './routes/w/donation-goal/$userId'
import { Route as WChatUserIdRouteImport } from './routes/w/chat/$userId'
import { Route as WAlertboxUserIdRouteImport } from './routes/w/alertbox/$userId'
import { Route as DashboardWidgetsSlugRouteImport } from './routes/dashboard/widgets/$slug'
import { Route as DashboardViewersIdRouteImport } from './routes/dashboard/viewers/$id'
import { Route as DashboardToolsTimersRouteImport } from './routes/dashboard/tools/timers'
import { Route as DashboardToolsHooksRouteImport } from './routes/dashboard/tools/hooks'
import { Route as DashboardToolsChatbotRouteImport } from './routes/dashboard/tools/chatbot'
import { Route as DashboardStreamHistoryIdRouteImport } from './routes/dashboard/stream-history/$id'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'
import { Route as DashboardAdminSupportRouteImport } from './routes/dashboard/admin/support'
import { Route as DashboardAdminNotificationsRouteImport } from './routes/dashboard/admin/notifications'
import { Route as DashboardToolsClipsIndexRouteImport } from './routes/dashboard/tools/clips/index'
import { Route as DashboardToolsClipsIdRouteImport } from './routes/dashboard/tools/clips/$id'
import { Route as DashboardScenesUserIdDisplayRouteImport } from './routes/dashboard/scenes/$userId/display'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStreamRoute = DashboardStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatHistoryRoute = DashboardChatHistoryRouteImport.update({
  id: '/chat-history',
  path: '/chat-history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWidgetsIndexRoute = DashboardWidgetsIndexRouteImport.update({
  id: '/widgets/',
  path: '/widgets/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardViewersIndexRoute = DashboardViewersIndexRouteImport.update({
  id: '/viewers/',
  path: '/viewers/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStreamHistoryIndexRoute =
  DashboardStreamHistoryIndexRouteImport.update({
    id: '/stream-history/',
    path: '/stream-history/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardScenesIndexRoute = DashboardScenesIndexRouteImport.update({
  id: '/scenes/',
  path: '/scenes/',
  getParentRoute: () => DashboardRoute,
} as any)
const WidgetsViewerCountObsRoute = WidgetsViewerCountObsRouteImport.update({
  id: '/widgets/viewer-count/obs',
  path: '/widgets/viewer-count/obs',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsTopDonorsObsRoute = WidgetsTopDonorsObsRouteImport.update({
  id: '/widgets/top-donors/obs',
  path: '/widgets/top-donors/obs',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsPollObsRoute = WidgetsPollObsRouteImport.update({
  id: '/widgets/poll/obs',
  path: '/widgets/poll/obs',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsFollowerCountObsRoute = WidgetsFollowerCountObsRouteImport.update({
  id: '/widgets/follower-count/obs',
  path: '/widgets/follower-count/obs',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsEventListObsRoute = WidgetsEventListObsRouteImport.update({
  id: '/widgets/event-list/obs',
  path: '/widgets/event-list/obs',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsDonationGoalObsRoute = WidgetsDonationGoalObsRouteImport.update({
  id: '/widgets/donation-goal/obs',
  path: '/widgets/donation-goal/obs',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsChatObsRoute = WidgetsChatObsRouteImport.update({
  id: '/widgets/chat/obs',
  path: '/widgets/chat/obs',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsAlertboxObsRoute = WidgetsAlertboxObsRouteImport.update({
  id: '/widgets/alertbox/obs',
  path: '/widgets/alertbox/obs',
  getParentRoute: () => rootRouteImport,
} as any)
const WViewerCountUserIdRoute = WViewerCountUserIdRouteImport.update({
  id: '/w/viewer-count/$userId',
  path: '/w/viewer-count/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WTopdonorsUserIdRoute = WTopdonorsUserIdRouteImport.update({
  id: '/w/topdonors/$userId',
  path: '/w/topdonors/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WTimerUserIdRoute = WTimerUserIdRouteImport.update({
  id: '/w/timer/$userId',
  path: '/w/timer/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WSmartCanvasUserIdRoute = WSmartCanvasUserIdRouteImport.update({
  id: '/w/smart-canvas/$userId',
  path: '/w/smart-canvas/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WSliderUserIdRoute = WSliderUserIdRouteImport.update({
  id: '/w/slider/$userId',
  path: '/w/slider/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WPollUserIdRoute = WPollUserIdRouteImport.update({
  id: '/w/poll/$userId',
  path: '/w/poll/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WPlaceholderUserIdRoute = WPlaceholderUserIdRouteImport.update({
  id: '/w/placeholder/$userId',
  path: '/w/placeholder/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WMessageHighlightUserIdRoute = WMessageHighlightUserIdRouteImport.update({
  id: '/w/message-highlight/$userId',
  path: '/w/message-highlight/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WGiveawayUserIdRoute = WGiveawayUserIdRouteImport.update({
  id: '/w/giveaway/$userId',
  path: '/w/giveaway/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WFollowerCountUserIdRoute = WFollowerCountUserIdRouteImport.update({
  id: '/w/follower-count/$userId',
  path: '/w/follower-count/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WEventlistUserIdRoute = WEventlistUserIdRouteImport.update({
  id: '/w/eventlist/$userId',
  path: '/w/eventlist/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WDonationGoalUserIdRoute = WDonationGoalUserIdRouteImport.update({
  id: '/w/donation-goal/$userId',
  path: '/w/donation-goal/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WChatUserIdRoute = WChatUserIdRouteImport.update({
  id: '/w/chat/$userId',
  path: '/w/chat/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WAlertboxUserIdRoute = WAlertboxUserIdRouteImport.update({
  id: '/w/alertbox/$userId',
  path: '/w/alertbox/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWidgetsSlugRoute = DashboardWidgetsSlugRouteImport.update({
  id: '/widgets/$slug',
  path: '/widgets/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardViewersIdRoute = DashboardViewersIdRouteImport.update({
  id: '/viewers/$id',
  path: '/viewers/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardToolsTimersRoute = DashboardToolsTimersRouteImport.update({
  id: '/tools/timers',
  path: '/tools/timers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardToolsHooksRoute = DashboardToolsHooksRouteImport.update({
  id: '/tools/hooks',
  path: '/tools/hooks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardToolsChatbotRoute = DashboardToolsChatbotRouteImport.update({
  id: '/tools/chatbot',
  path: '/tools/chatbot',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStreamHistoryIdRoute =
  DashboardStreamHistoryIdRouteImport.update({
    id: '/stream-history/$id',
    path: '/stream-history/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminSupportRoute = DashboardAdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminNotificationsRoute =
  DashboardAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardToolsClipsIndexRoute =
  DashboardToolsClipsIndexRouteImport.update({
    id: '/tools/clips/',
    path: '/tools/clips/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardToolsClipsIdRoute = DashboardToolsClipsIdRouteImport.update({
  id: '/tools/clips/$id',
  path: '/tools/clips/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScenesUserIdDisplayRoute =
  DashboardScenesUserIdDisplayRouteImport.update({
    id: '/scenes/$userId/display',
    path: '/scenes/$userId/display',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/chat-history': typeof DashboardChatHistoryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stream': typeof DashboardStreamRoute
  '/u/$username': typeof UUsernameRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/notifications': typeof DashboardAdminNotificationsRoute
  '/dashboard/admin/support': typeof DashboardAdminSupportRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/stream-history/$id': typeof DashboardStreamHistoryIdRoute
  '/dashboard/tools/chatbot': typeof DashboardToolsChatbotRoute
  '/dashboard/tools/hooks': typeof DashboardToolsHooksRoute
  '/dashboard/tools/timers': typeof DashboardToolsTimersRoute
  '/dashboard/viewers/$id': typeof DashboardViewersIdRoute
  '/dashboard/widgets/$slug': typeof DashboardWidgetsSlugRoute
  '/w/alertbox/$userId': typeof WAlertboxUserIdRoute
  '/w/chat/$userId': typeof WChatUserIdRoute
  '/w/donation-goal/$userId': typeof WDonationGoalUserIdRoute
  '/w/eventlist/$userId': typeof WEventlistUserIdRoute
  '/w/follower-count/$userId': typeof WFollowerCountUserIdRoute
  '/w/giveaway/$userId': typeof WGiveawayUserIdRoute
  '/w/message-highlight/$userId': typeof WMessageHighlightUserIdRoute
  '/w/placeholder/$userId': typeof WPlaceholderUserIdRoute
  '/w/poll/$userId': typeof WPollUserIdRoute
  '/w/slider/$userId': typeof WSliderUserIdRoute
  '/w/smart-canvas/$userId': typeof WSmartCanvasUserIdRoute
  '/w/timer/$userId': typeof WTimerUserIdRoute
  '/w/topdonors/$userId': typeof WTopdonorsUserIdRoute
  '/w/viewer-count/$userId': typeof WViewerCountUserIdRoute
  '/widgets/alertbox/obs': typeof WidgetsAlertboxObsRoute
  '/widgets/chat/obs': typeof WidgetsChatObsRoute
  '/widgets/donation-goal/obs': typeof WidgetsDonationGoalObsRoute
  '/widgets/event-list/obs': typeof WidgetsEventListObsRoute
  '/widgets/follower-count/obs': typeof WidgetsFollowerCountObsRoute
  '/widgets/poll/obs': typeof WidgetsPollObsRoute
  '/widgets/top-donors/obs': typeof WidgetsTopDonorsObsRoute
  '/widgets/viewer-count/obs': typeof WidgetsViewerCountObsRoute
  '/dashboard/scenes/': typeof DashboardScenesIndexRoute
  '/dashboard/stream-history/': typeof DashboardStreamHistoryIndexRoute
  '/dashboard/viewers/': typeof DashboardViewersIndexRoute
  '/dashboard/widgets/': typeof DashboardWidgetsIndexRoute
  '/dashboard/scenes/$userId/display': typeof DashboardScenesUserIdDisplayRoute
  '/dashboard/tools/clips/$id': typeof DashboardToolsClipsIdRoute
  '/dashboard/tools/clips/': typeof DashboardToolsClipsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/chat-history': typeof DashboardChatHistoryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stream': typeof DashboardStreamRoute
  '/u/$username': typeof UUsernameRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/notifications': typeof DashboardAdminNotificationsRoute
  '/dashboard/admin/support': typeof DashboardAdminSupportRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/stream-history/$id': typeof DashboardStreamHistoryIdRoute
  '/dashboard/tools/chatbot': typeof DashboardToolsChatbotRoute
  '/dashboard/tools/hooks': typeof DashboardToolsHooksRoute
  '/dashboard/tools/timers': typeof DashboardToolsTimersRoute
  '/dashboard/viewers/$id': typeof DashboardViewersIdRoute
  '/dashboard/widgets/$slug': typeof DashboardWidgetsSlugRoute
  '/w/alertbox/$userId': typeof WAlertboxUserIdRoute
  '/w/chat/$userId': typeof WChatUserIdRoute
  '/w/donation-goal/$userId': typeof WDonationGoalUserIdRoute
  '/w/eventlist/$userId': typeof WEventlistUserIdRoute
  '/w/follower-count/$userId': typeof WFollowerCountUserIdRoute
  '/w/giveaway/$userId': typeof WGiveawayUserIdRoute
  '/w/message-highlight/$userId': typeof WMessageHighlightUserIdRoute
  '/w/placeholder/$userId': typeof WPlaceholderUserIdRoute
  '/w/poll/$userId': typeof WPollUserIdRoute
  '/w/slider/$userId': typeof WSliderUserIdRoute
  '/w/smart-canvas/$userId': typeof WSmartCanvasUserIdRoute
  '/w/timer/$userId': typeof WTimerUserIdRoute
  '/w/topdonors/$userId': typeof WTopdonorsUserIdRoute
  '/w/viewer-count/$userId': typeof WViewerCountUserIdRoute
  '/widgets/alertbox/obs': typeof WidgetsAlertboxObsRoute
  '/widgets/chat/obs': typeof WidgetsChatObsRoute
  '/widgets/donation-goal/obs': typeof WidgetsDonationGoalObsRoute
  '/widgets/event-list/obs': typeof WidgetsEventListObsRoute
  '/widgets/follower-count/obs': typeof WidgetsFollowerCountObsRoute
  '/widgets/poll/obs': typeof WidgetsPollObsRoute
  '/widgets/top-donors/obs': typeof WidgetsTopDonorsObsRoute
  '/widgets/viewer-count/obs': typeof WidgetsViewerCountObsRoute
  '/dashboard/scenes': typeof DashboardScenesIndexRoute
  '/dashboard/stream-history': typeof DashboardStreamHistoryIndexRoute
  '/dashboard/viewers': typeof DashboardViewersIndexRoute
  '/dashboard/widgets': typeof DashboardWidgetsIndexRoute
  '/dashboard/scenes/$userId/display': typeof DashboardScenesUserIdDisplayRoute
  '/dashboard/tools/clips/$id': typeof DashboardToolsClipsIdRoute
  '/dashboard/tools/clips': typeof DashboardToolsClipsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/chat-history': typeof DashboardChatHistoryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stream': typeof DashboardStreamRoute
  '/u/$username': typeof UUsernameRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/notifications': typeof DashboardAdminNotificationsRoute
  '/dashboard/admin/support': typeof DashboardAdminSupportRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/stream-history/$id': typeof DashboardStreamHistoryIdRoute
  '/dashboard/tools/chatbot': typeof DashboardToolsChatbotRoute
  '/dashboard/tools/hooks': typeof DashboardToolsHooksRoute
  '/dashboard/tools/timers': typeof DashboardToolsTimersRoute
  '/dashboard/viewers/$id': typeof DashboardViewersIdRoute
  '/dashboard/widgets/$slug': typeof DashboardWidgetsSlugRoute
  '/w/alertbox/$userId': typeof WAlertboxUserIdRoute
  '/w/chat/$userId': typeof WChatUserIdRoute
  '/w/donation-goal/$userId': typeof WDonationGoalUserIdRoute
  '/w/eventlist/$userId': typeof WEventlistUserIdRoute
  '/w/follower-count/$userId': typeof WFollowerCountUserIdRoute
  '/w/giveaway/$userId': typeof WGiveawayUserIdRoute
  '/w/message-highlight/$userId': typeof WMessageHighlightUserIdRoute
  '/w/placeholder/$userId': typeof WPlaceholderUserIdRoute
  '/w/poll/$userId': typeof WPollUserIdRoute
  '/w/slider/$userId': typeof WSliderUserIdRoute
  '/w/smart-canvas/$userId': typeof WSmartCanvasUserIdRoute
  '/w/timer/$userId': typeof WTimerUserIdRoute
  '/w/topdonors/$userId': typeof WTopdonorsUserIdRoute
  '/w/viewer-count/$userId': typeof WViewerCountUserIdRoute
  '/widgets/alertbox/obs': typeof WidgetsAlertboxObsRoute
  '/widgets/chat/obs': typeof WidgetsChatObsRoute
  '/widgets/donation-goal/obs': typeof WidgetsDonationGoalObsRoute
  '/widgets/event-list/obs': typeof WidgetsEventListObsRoute
  '/widgets/follower-count/obs': typeof WidgetsFollowerCountObsRoute
  '/widgets/poll/obs': typeof WidgetsPollObsRoute
  '/widgets/top-donors/obs': typeof WidgetsTopDonorsObsRoute
  '/widgets/viewer-count/obs': typeof WidgetsViewerCountObsRoute
  '/dashboard/scenes/': typeof DashboardScenesIndexRoute
  '/dashboard/stream-history/': typeof DashboardStreamHistoryIndexRoute
  '/dashboard/viewers/': typeof DashboardViewersIndexRoute
  '/dashboard/widgets/': typeof DashboardWidgetsIndexRoute
  '/dashboard/scenes/$userId/display': typeof DashboardScenesUserIdDisplayRoute
  '/dashboard/tools/clips/$id': typeof DashboardToolsClipsIdRoute
  '/dashboard/tools/clips/': typeof DashboardToolsClipsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/chat-history'
    | '/dashboard/settings'
    | '/dashboard/stream'
    | '/u/$username'
    | '/dashboard/'
    | '/dashboard/admin/notifications'
    | '/dashboard/admin/support'
    | '/dashboard/admin/users'
    | '/dashboard/stream-history/$id'
    | '/dashboard/tools/chatbot'
    | '/dashboard/tools/hooks'
    | '/dashboard/tools/timers'
    | '/dashboard/viewers/$id'
    | '/dashboard/widgets/$slug'
    | '/w/alertbox/$userId'
    | '/w/chat/$userId'
    | '/w/donation-goal/$userId'
    | '/w/eventlist/$userId'
    | '/w/follower-count/$userId'
    | '/w/giveaway/$userId'
    | '/w/message-highlight/$userId'
    | '/w/placeholder/$userId'
    | '/w/poll/$userId'
    | '/w/slider/$userId'
    | '/w/smart-canvas/$userId'
    | '/w/timer/$userId'
    | '/w/topdonors/$userId'
    | '/w/viewer-count/$userId'
    | '/widgets/alertbox/obs'
    | '/widgets/chat/obs'
    | '/widgets/donation-goal/obs'
    | '/widgets/event-list/obs'
    | '/widgets/follower-count/obs'
    | '/widgets/poll/obs'
    | '/widgets/top-donors/obs'
    | '/widgets/viewer-count/obs'
    | '/dashboard/scenes/'
    | '/dashboard/stream-history/'
    | '/dashboard/viewers/'
    | '/dashboard/widgets/'
    | '/dashboard/scenes/$userId/display'
    | '/dashboard/tools/clips/$id'
    | '/dashboard/tools/clips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/chat-history'
    | '/dashboard/settings'
    | '/dashboard/stream'
    | '/u/$username'
    | '/dashboard'
    | '/dashboard/admin/notifications'
    | '/dashboard/admin/support'
    | '/dashboard/admin/users'
    | '/dashboard/stream-history/$id'
    | '/dashboard/tools/chatbot'
    | '/dashboard/tools/hooks'
    | '/dashboard/tools/timers'
    | '/dashboard/viewers/$id'
    | '/dashboard/widgets/$slug'
    | '/w/alertbox/$userId'
    | '/w/chat/$userId'
    | '/w/donation-goal/$userId'
    | '/w/eventlist/$userId'
    | '/w/follower-count/$userId'
    | '/w/giveaway/$userId'
    | '/w/message-highlight/$userId'
    | '/w/placeholder/$userId'
    | '/w/poll/$userId'
    | '/w/slider/$userId'
    | '/w/smart-canvas/$userId'
    | '/w/timer/$userId'
    | '/w/topdonors/$userId'
    | '/w/viewer-count/$userId'
    | '/widgets/alertbox/obs'
    | '/widgets/chat/obs'
    | '/widgets/donation-goal/obs'
    | '/widgets/event-list/obs'
    | '/widgets/follower-count/obs'
    | '/widgets/poll/obs'
    | '/widgets/top-donors/obs'
    | '/widgets/viewer-count/obs'
    | '/dashboard/scenes'
    | '/dashboard/stream-history'
    | '/dashboard/viewers'
    | '/dashboard/widgets'
    | '/dashboard/scenes/$userId/display'
    | '/dashboard/tools/clips/$id'
    | '/dashboard/tools/clips'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/chat-history'
    | '/dashboard/settings'
    | '/dashboard/stream'
    | '/u/$username'
    | '/dashboard/'
    | '/dashboard/admin/notifications'
    | '/dashboard/admin/support'
    | '/dashboard/admin/users'
    | '/dashboard/stream-history/$id'
    | '/dashboard/tools/chatbot'
    | '/dashboard/tools/hooks'
    | '/dashboard/tools/timers'
    | '/dashboard/viewers/$id'
    | '/dashboard/widgets/$slug'
    | '/w/alertbox/$userId'
    | '/w/chat/$userId'
    | '/w/donation-goal/$userId'
    | '/w/eventlist/$userId'
    | '/w/follower-count/$userId'
    | '/w/giveaway/$userId'
    | '/w/message-highlight/$userId'
    | '/w/placeholder/$userId'
    | '/w/poll/$userId'
    | '/w/slider/$userId'
    | '/w/smart-canvas/$userId'
    | '/w/timer/$userId'
    | '/w/topdonors/$userId'
    | '/w/viewer-count/$userId'
    | '/widgets/alertbox/obs'
    | '/widgets/chat/obs'
    | '/widgets/donation-goal/obs'
    | '/widgets/event-list/obs'
    | '/widgets/follower-count/obs'
    | '/widgets/poll/obs'
    | '/widgets/top-donors/obs'
    | '/widgets/viewer-count/obs'
    | '/dashboard/scenes/'
    | '/dashboard/stream-history/'
    | '/dashboard/viewers/'
    | '/dashboard/widgets/'
    | '/dashboard/scenes/$userId/display'
    | '/dashboard/tools/clips/$id'
    | '/dashboard/tools/clips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  UUsernameRoute: typeof UUsernameRoute
  WAlertboxUserIdRoute: typeof WAlertboxUserIdRoute
  WChatUserIdRoute: typeof WChatUserIdRoute
  WDonationGoalUserIdRoute: typeof WDonationGoalUserIdRoute
  WEventlistUserIdRoute: typeof WEventlistUserIdRoute
  WFollowerCountUserIdRoute: typeof WFollowerCountUserIdRoute
  WGiveawayUserIdRoute: typeof WGiveawayUserIdRoute
  WMessageHighlightUserIdRoute: typeof WMessageHighlightUserIdRoute
  WPlaceholderUserIdRoute: typeof WPlaceholderUserIdRoute
  WPollUserIdRoute: typeof WPollUserIdRoute
  WSliderUserIdRoute: typeof WSliderUserIdRoute
  WSmartCanvasUserIdRoute: typeof WSmartCanvasUserIdRoute
  WTimerUserIdRoute: typeof WTimerUserIdRoute
  WTopdonorsUserIdRoute: typeof WTopdonorsUserIdRoute
  WViewerCountUserIdRoute: typeof WViewerCountUserIdRoute
  WidgetsAlertboxObsRoute: typeof WidgetsAlertboxObsRoute
  WidgetsChatObsRoute: typeof WidgetsChatObsRoute
  WidgetsDonationGoalObsRoute: typeof WidgetsDonationGoalObsRoute
  WidgetsEventListObsRoute: typeof WidgetsEventListObsRoute
  WidgetsFollowerCountObsRoute: typeof WidgetsFollowerCountObsRoute
  WidgetsPollObsRoute: typeof WidgetsPollObsRoute
  WidgetsTopDonorsObsRoute: typeof WidgetsTopDonorsObsRoute
  WidgetsViewerCountObsRoute: typeof WidgetsViewerCountObsRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/stream': {
      id: '/dashboard/stream'
      path: '/stream'
      fullPath: '/dashboard/stream'
      preLoaderRoute: typeof DashboardStreamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat-history': {
      id: '/dashboard/chat-history'
      path: '/chat-history'
      fullPath: '/dashboard/chat-history'
      preLoaderRoute: typeof DashboardChatHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/widgets/': {
      id: '/dashboard/widgets/'
      path: '/widgets'
      fullPath: '/dashboard/widgets/'
      preLoaderRoute: typeof DashboardWidgetsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/viewers/': {
      id: '/dashboard/viewers/'
      path: '/viewers'
      fullPath: '/dashboard/viewers/'
      preLoaderRoute: typeof DashboardViewersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stream-history/': {
      id: '/dashboard/stream-history/'
      path: '/stream-history'
      fullPath: '/dashboard/stream-history/'
      preLoaderRoute: typeof DashboardStreamHistoryIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scenes/': {
      id: '/dashboard/scenes/'
      path: '/scenes'
      fullPath: '/dashboard/scenes/'
      preLoaderRoute: typeof DashboardScenesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/widgets/viewer-count/obs': {
      id: '/widgets/viewer-count/obs'
      path: '/widgets/viewer-count/obs'
      fullPath: '/widgets/viewer-count/obs'
      preLoaderRoute: typeof WidgetsViewerCountObsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/top-donors/obs': {
      id: '/widgets/top-donors/obs'
      path: '/widgets/top-donors/obs'
      fullPath: '/widgets/top-donors/obs'
      preLoaderRoute: typeof WidgetsTopDonorsObsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/poll/obs': {
      id: '/widgets/poll/obs'
      path: '/widgets/poll/obs'
      fullPath: '/widgets/poll/obs'
      preLoaderRoute: typeof WidgetsPollObsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/follower-count/obs': {
      id: '/widgets/follower-count/obs'
      path: '/widgets/follower-count/obs'
      fullPath: '/widgets/follower-count/obs'
      preLoaderRoute: typeof WidgetsFollowerCountObsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/event-list/obs': {
      id: '/widgets/event-list/obs'
      path: '/widgets/event-list/obs'
      fullPath: '/widgets/event-list/obs'
      preLoaderRoute: typeof WidgetsEventListObsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/donation-goal/obs': {
      id: '/widgets/donation-goal/obs'
      path: '/widgets/donation-goal/obs'
      fullPath: '/widgets/donation-goal/obs'
      preLoaderRoute: typeof WidgetsDonationGoalObsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/chat/obs': {
      id: '/widgets/chat/obs'
      path: '/widgets/chat/obs'
      fullPath: '/widgets/chat/obs'
      preLoaderRoute: typeof WidgetsChatObsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/alertbox/obs': {
      id: '/widgets/alertbox/obs'
      path: '/widgets/alertbox/obs'
      fullPath: '/widgets/alertbox/obs'
      preLoaderRoute: typeof WidgetsAlertboxObsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/viewer-count/$userId': {
      id: '/w/viewer-count/$userId'
      path: '/w/viewer-count/$userId'
      fullPath: '/w/viewer-count/$userId'
      preLoaderRoute: typeof WViewerCountUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/topdonors/$userId': {
      id: '/w/topdonors/$userId'
      path: '/w/topdonors/$userId'
      fullPath: '/w/topdonors/$userId'
      preLoaderRoute: typeof WTopdonorsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/timer/$userId': {
      id: '/w/timer/$userId'
      path: '/w/timer/$userId'
      fullPath: '/w/timer/$userId'
      preLoaderRoute: typeof WTimerUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/smart-canvas/$userId': {
      id: '/w/smart-canvas/$userId'
      path: '/w/smart-canvas/$userId'
      fullPath: '/w/smart-canvas/$userId'
      preLoaderRoute: typeof WSmartCanvasUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/slider/$userId': {
      id: '/w/slider/$userId'
      path: '/w/slider/$userId'
      fullPath: '/w/slider/$userId'
      preLoaderRoute: typeof WSliderUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/poll/$userId': {
      id: '/w/poll/$userId'
      path: '/w/poll/$userId'
      fullPath: '/w/poll/$userId'
      preLoaderRoute: typeof WPollUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/placeholder/$userId': {
      id: '/w/placeholder/$userId'
      path: '/w/placeholder/$userId'
      fullPath: '/w/placeholder/$userId'
      preLoaderRoute: typeof WPlaceholderUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/message-highlight/$userId': {
      id: '/w/message-highlight/$userId'
      path: '/w/message-highlight/$userId'
      fullPath: '/w/message-highlight/$userId'
      preLoaderRoute: typeof WMessageHighlightUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/giveaway/$userId': {
      id: '/w/giveaway/$userId'
      path: '/w/giveaway/$userId'
      fullPath: '/w/giveaway/$userId'
      preLoaderRoute: typeof WGiveawayUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/follower-count/$userId': {
      id: '/w/follower-count/$userId'
      path: '/w/follower-count/$userId'
      fullPath: '/w/follower-count/$userId'
      preLoaderRoute: typeof WFollowerCountUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/eventlist/$userId': {
      id: '/w/eventlist/$userId'
      path: '/w/eventlist/$userId'
      fullPath: '/w/eventlist/$userId'
      preLoaderRoute: typeof WEventlistUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/donation-goal/$userId': {
      id: '/w/donation-goal/$userId'
      path: '/w/donation-goal/$userId'
      fullPath: '/w/donation-goal/$userId'
      preLoaderRoute: typeof WDonationGoalUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/chat/$userId': {
      id: '/w/chat/$userId'
      path: '/w/chat/$userId'
      fullPath: '/w/chat/$userId'
      preLoaderRoute: typeof WChatUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/alertbox/$userId': {
      id: '/w/alertbox/$userId'
      path: '/w/alertbox/$userId'
      fullPath: '/w/alertbox/$userId'
      preLoaderRoute: typeof WAlertboxUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/widgets/$slug': {
      id: '/dashboard/widgets/$slug'
      path: '/widgets/$slug'
      fullPath: '/dashboard/widgets/$slug'
      preLoaderRoute: typeof DashboardWidgetsSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/viewers/$id': {
      id: '/dashboard/viewers/$id'
      path: '/viewers/$id'
      fullPath: '/dashboard/viewers/$id'
      preLoaderRoute: typeof DashboardViewersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tools/timers': {
      id: '/dashboard/tools/timers'
      path: '/tools/timers'
      fullPath: '/dashboard/tools/timers'
      preLoaderRoute: typeof DashboardToolsTimersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tools/hooks': {
      id: '/dashboard/tools/hooks'
      path: '/tools/hooks'
      fullPath: '/dashboard/tools/hooks'
      preLoaderRoute: typeof DashboardToolsHooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tools/chatbot': {
      id: '/dashboard/tools/chatbot'
      path: '/tools/chatbot'
      fullPath: '/dashboard/tools/chatbot'
      preLoaderRoute: typeof DashboardToolsChatbotRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stream-history/$id': {
      id: '/dashboard/stream-history/$id'
      path: '/stream-history/$id'
      fullPath: '/dashboard/stream-history/$id'
      preLoaderRoute: typeof DashboardStreamHistoryIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/support': {
      id: '/dashboard/admin/support'
      path: '/admin/support'
      fullPath: '/dashboard/admin/support'
      preLoaderRoute: typeof DashboardAdminSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/notifications': {
      id: '/dashboard/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/dashboard/admin/notifications'
      preLoaderRoute: typeof DashboardAdminNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tools/clips/': {
      id: '/dashboard/tools/clips/'
      path: '/tools/clips'
      fullPath: '/dashboard/tools/clips/'
      preLoaderRoute: typeof DashboardToolsClipsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tools/clips/$id': {
      id: '/dashboard/tools/clips/$id'
      path: '/tools/clips/$id'
      fullPath: '/dashboard/tools/clips/$id'
      preLoaderRoute: typeof DashboardToolsClipsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scenes/$userId/display': {
      id: '/dashboard/scenes/$userId/display'
      path: '/scenes/$userId/display'
      fullPath: '/dashboard/scenes/$userId/display'
      preLoaderRoute: typeof DashboardScenesUserIdDisplayRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardChatHistoryRoute: typeof DashboardChatHistoryRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStreamRoute: typeof DashboardStreamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminNotificationsRoute: typeof DashboardAdminNotificationsRoute
  DashboardAdminSupportRoute: typeof DashboardAdminSupportRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardStreamHistoryIdRoute: typeof DashboardStreamHistoryIdRoute
  DashboardToolsChatbotRoute: typeof DashboardToolsChatbotRoute
  DashboardToolsHooksRoute: typeof DashboardToolsHooksRoute
  DashboardToolsTimersRoute: typeof DashboardToolsTimersRoute
  DashboardViewersIdRoute: typeof DashboardViewersIdRoute
  DashboardWidgetsSlugRoute: typeof DashboardWidgetsSlugRoute
  DashboardScenesIndexRoute: typeof DashboardScenesIndexRoute
  DashboardStreamHistoryIndexRoute: typeof DashboardStreamHistoryIndexRoute
  DashboardViewersIndexRoute: typeof DashboardViewersIndexRoute
  DashboardWidgetsIndexRoute: typeof DashboardWidgetsIndexRoute
  DashboardScenesUserIdDisplayRoute: typeof DashboardScenesUserIdDisplayRoute
  DashboardToolsClipsIdRoute: typeof DashboardToolsClipsIdRoute
  DashboardToolsClipsIndexRoute: typeof DashboardToolsClipsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardChatHistoryRoute: DashboardChatHistoryRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStreamRoute: DashboardStreamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminNotificationsRoute: DashboardAdminNotificationsRoute,
  DashboardAdminSupportRoute: DashboardAdminSupportRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardStreamHistoryIdRoute: DashboardStreamHistoryIdRoute,
  DashboardToolsChatbotRoute: DashboardToolsChatbotRoute,
  DashboardToolsHooksRoute: DashboardToolsHooksRoute,
  DashboardToolsTimersRoute: DashboardToolsTimersRoute,
  DashboardViewersIdRoute: DashboardViewersIdRoute,
  DashboardWidgetsSlugRoute: DashboardWidgetsSlugRoute,
  DashboardScenesIndexRoute: DashboardScenesIndexRoute,
  DashboardStreamHistoryIndexRoute: DashboardStreamHistoryIndexRoute,
  DashboardViewersIndexRoute: DashboardViewersIndexRoute,
  DashboardWidgetsIndexRoute: DashboardWidgetsIndexRoute,
  DashboardScenesUserIdDisplayRoute: DashboardScenesUserIdDisplayRoute,
  DashboardToolsClipsIdRoute: DashboardToolsClipsIdRoute,
  DashboardToolsClipsIndexRoute: DashboardToolsClipsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  UUsernameRoute: UUsernameRoute,
  WAlertboxUserIdRoute: WAlertboxUserIdRoute,
  WChatUserIdRoute: WChatUserIdRoute,
  WDonationGoalUserIdRoute: WDonationGoalUserIdRoute,
  WEventlistUserIdRoute: WEventlistUserIdRoute,
  WFollowerCountUserIdRoute: WFollowerCountUserIdRoute,
  WGiveawayUserIdRoute: WGiveawayUserIdRoute,
  WMessageHighlightUserIdRoute: WMessageHighlightUserIdRoute,
  WPlaceholderUserIdRoute: WPlaceholderUserIdRoute,
  WPollUserIdRoute: WPollUserIdRoute,
  WSliderUserIdRoute: WSliderUserIdRoute,
  WSmartCanvasUserIdRoute: WSmartCanvasUserIdRoute,
  WTimerUserIdRoute: WTimerUserIdRoute,
  WTopdonorsUserIdRoute: WTopdonorsUserIdRoute,
  WViewerCountUserIdRoute: WViewerCountUserIdRoute,
  WidgetsAlertboxObsRoute: WidgetsAlertboxObsRoute,
  WidgetsChatObsRoute: WidgetsChatObsRoute,
  WidgetsDonationGoalObsRoute: WidgetsDonationGoalObsRoute,
  WidgetsEventListObsRoute: WidgetsEventListObsRoute,
  WidgetsFollowerCountObsRoute: WidgetsFollowerCountObsRoute,
  WidgetsPollObsRoute: WidgetsPollObsRoute,
  WidgetsTopDonorsObsRoute: WidgetsTopDonorsObsRoute,
  WidgetsViewerCountObsRoute: WidgetsViewerCountObsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
