name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches: ["master", "main"]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'workflow_run' && github.event.workflow_run.head_branch == 'master'
    
    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: static.245.61.108.65.clients.your-server.de
          username: root
          script: |
            cd streampai-elixir
            git pull
            docker compose -f docker-compose.prod.yml up -d