name: Integration Tests

on:
  schedule:
    # Run daily at midnight UTC
    - cron: "0 0 * * *"
  # Also allow manual triggering
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    environment: prod
    env:
      MIX_ENV: test
      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: streampai_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.18.4"
          otp-version: "27.2"

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: |
          cd backend
          mix deps.get

      - name: Setup database
        run: |
          cd backend
          mix ash.setup --quiet

      - name: Run integration tests
        run: |
          cd backend
          mix test --only integration --max-failures 10

      - name: Notify on failure
        if: failure()
        run: |
          echo "Integration tests failed! Check the logs for details."
          echo "This likely indicates changes in external API contracts."
